enum TypeChoix {
  ACTION,
  PIOCHE,
  PERSONNAGE,
  RETRAIT_PERSONNAGE,
  GARDER_BATIMENT,
  CONSTRUIRE_BATIMENT,
  CIBLE_MAGICIEN,
  CIBLE_VOLEUR,
  CIBLE_ASSASSIN,
  CIBLE_CONDOTTIERE
}

export default TypeChoix;