enum TypeChoix {
  ACTION = "ACTION",
  PIOCHE = "PIOCHE",
  PERSONNAGE = "PERSONNAGE",
  RETRAIT_PERSONNAGE = "RETRAIT_PERSONNAGE",
  GARDER_BATIMENT = "GARDER_BATIMENT",
  CONSTRUIRE_BATIMENT = "CONSTRUIRE_BATIMENT",
  CIBLE_MAGICIEN = "CIBLE_MAGICIEN",
  CIBLE_VOLEUR = "CIBLE_VOLEUR",
  CIBLE_ASSASSIN = "CIBLE_ASSASSIN",
  CIBLE_CONDOTTIERE = "CIBLE_CONDOTTIERE",
}

export default TypeChoix;